AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Resources:
  processtxnsfile:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: process_txns_file.handler
      Runtime: python3.9
      CodeUri: ./app
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TxnTable
        - S3CrudPolicy:
            BucketName: !Ref Bucket1
      Environment:
        Variables:
          TABLE_TXN: !Ref TxnTable
          AWS_REGION: us-east-1
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: stori_account_
                  - Name: suffix
                    Value: .csv

  TxnTable:
    Type: AWS::Serverless::SimpleTable
  Bucket1:
    Type: 'AWS::S3::Bucket'
