AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Resources:
  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt ProcessTxnsFile.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceAccount: !Sub ${AWS::AccountId}
      SourceArn: !GetAtt InputBucket.Arn
  TxnTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: txn_id
        Type: String
  InputBucket:
    Type: 'AWS::S3::Bucket'
  ProcessTxnsFile:
    Type: 'AWS::Serverless::Function'
    Properties:
      PackageType: Image
      Policies:
        - SESCrudPolicy:
            IdentityName: '*'
        - S3FullAccessPolicy:
            BucketName: '*'
        - DynamoDBCrudPolicy:
            TableName: !Ref TxnTable
      Handler: process_txns_file.handler
      Runtime: python3.9
      CodeUri: ./app
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_TXN: !Ref TxnTable
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: InputBucket
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: stori_account_
                  - Name: suffix
                    Value: .csv
    Metadata:
      DockerTag: !Sub '${AWS::StackName}-ProcessTransactionsFile-v1.0.0'
      DockerContext: ./draft_profiles
      Dockerfile: Dockerfile
Outputs:
  ProcessTxnsFileFunction:
    Description: "Process Transactions File Function ARN"
    Value: !GetAtt ProcessTxnsFile.Arn
  HelloWorldFunctionIamRole:
    Description: "Bucket name for Process Transactions File function"
    Value: !GetAtt InputBucket.Arn
